apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

labels:
- pairs:
    environment: staging

replicas:
- name: web-app
  count: 3

patchesJson6902:
- target:
    group: v1
    version: v1
    kind: Service
    name: web-service
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
