apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- ../../base

labels:
- pairs:
    environment: development

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: web-config
  behavior: merge
  literals:
  - log_level=debug
  - debug_mode=true
