apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: advanced-rbac
  name: admin-rolebinding
subjects:
- kind: User
  name: admin-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
