apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: advanced-rbac
  name: advanced-dev-binding
subjects:
- kind: User
  name: advanced-dev-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: advanced-developer
  apiGroup: rbac.authorization.k8s.io
