apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: advanced-rbac
  name: advanced-developer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "update"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: ["blue-pod", "green-pod"]
  verbs: ["get", "list"]
