apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rbac-lab
  name: dev-user-binding
subjects:
- kind: User
  name: dev-user  # Replace with actual user name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
