apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  containers:
    - name: web-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: web-data
  volumes:
    - name: web-data
      persistentVolumeClaim:
        claimName: my-pvc
