
# Create a new pod called custom-nginx 
# using the nginx image and run it 
# on container port 8080

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: custom-nginx
  name: custom-nginx
spec:
  containers:
  - image: nginx
    name: custom-nginx
    ports:
    - containerPort: 8080