apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    app: red
spec: 
  selector:
    matchLabels:
      app: red
  replicas: 2
  template:
    metadata:
      labels:
        app: red
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exist
      containers:
      - name: nginx
        image: nginx
