apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- hpa.yaml

labels:
- pairs:
    environment: production

replicas:
- name: web-app
  count: 5

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml

configMapGenerator:
- name: web-config
  behavior: replace
  literals:
  - database_url=prod-db.example.com:5432
  - log_level=warn
  - max_connections=500
